version: '3.8'

services:
  app:
    build:
      context: .
    container_name: social-media-app
    env_file:
      - .env
    ports:
      - 3001:3000
    depends_on:
      - postgresql
    environment:
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=docker
      - DB_PASSWORD=docker
      - DB_NAME=social-media-db
    networks:
    - social-media

  postgresql:
    container_name: postgresql
    image: bitnami/postgresql
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=social-media-db
    volumes:
      - postgresql_data:/bitnami/postgresql
    networks:
    - social-media

networks:
  social-media:
    name: social-media
    driver: bridge

volumes:
  postgresql_data:
