name: Continuous Integration

on: pull_request

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        env:
          POSTGRES_USER: docker
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: social-media-db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U docker"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.x

      - name: Install dependencies
        run: pnpm install

      - name: Run migrations
        run: pnpm migrate:push

      - name: Run build and test
        run: |
          pnpm build
          pnpm test
